server:
  port: 8080

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://host.docker.internal:8082/eureka